# Data in R

**[R]{.sans-serif}** can recognize, store, extract, and use different kinds of data. In the previous section we saw how to do all this with numerical vectors. But working with real data requires using multiple types of data with different shapes and sizes. In this section we will learn how **[R]{.sans-serif}** deals with these data structures, and how to use them to study and summarize data.

## Data types

 + **Numeric, aka doubles**: Regular numbers with a decimal value (which may be zero). The numbers can be positive or negative, large or small. In general, R will save any number that you type in R as a double.
 + **Integers**: Integer vectors store integers, numbers that can be written without a decimal component. Data scientists often don't need integers because we can save them as doubles.
 + **Logicals**: Logical vectors store `TRUE` and `FALSE`, R's form of Boolean data.

## Data structures

The first step is to know the different types of data that **[R]{.sans-serif}** can understand. And the simplest data structure is an atomic vector.

### Atomic vectors

An atomic vector is a simple vector of data. To create an atomic vector, we can group some numbers together using the combine function `c()`. In the last section we worked with the atomic vector of temperatures for countries: 

```{r atomic vector}
temperatures_fahrenheit <- c(50, 90, 65, -10)
```

Atomic vectors can have almost^[The maximum length (number of elements) of a vector is 2^31 - 1 ~ 2*10^9. See [here](https://en.wikipedia.org/wiki/Floppy_disk) for more information.] as many elements as you want---including zero!