project:
  type: book
  output-dir: docs

book:
  title: "Introduction to R"
  sidebar:
    title: "Introduction to R"
  chapters:
    - index.qmd
    - 01_the_r_environment.qmd
    - 02_getting_started_with_r.qmd
    - 03_data_in_r.qmd
    - 04_basic_data_processing.qmd

format:
  html:
    theme:
      light: cosmo
      dark: [cosmo, theme-dark.scss]
    callout-appearance: simple
