project:
  type: book
  output-dir: docs

book:
  title: "Introduction to R"
  sidebar:
    title: "Introduction to R"
  chapters:
    - index.qmd
    - notes.qmd

format:
  html:
    theme:
      light: cosmo
      dark: [cosmo, theme-dark.scss]
    callout-appearance: simple
