---
engine: knitr
---

Last modified: `r Sys.Date()`

# Preface {.unnumbered}

## Who are this notes for? {.unnumbered}

These notes are a intended for anyone that wants to use **R** but has little or 
no experience using it, and little or no experience in programming. These notes are self-contained and form the basis for in-person workshops hosted by CSCAR (see contact information below). During the workshops, we also use a slideshow based on these notes. This slideshow is available [here](https://cscar.github.io/workshop-r-intro/slideshow.html).

## Creation of this document {.unnumbered}

These notes are published using [Quarto](https://quarto.org). Their source code is available at <https://github.com/CSCAR/workshop-r-intro>.

You can switch between light and dark modes using the button in the top left 
corner of the screen. Dark mode reverses the colors of the images to reduce 
brightness. To show an image in its original colors, move your mouse over it
(or press it if you are on a mobile device). All images link to more detailed 
full-size versions.

## Contact information {.unnumbered}

### CSCAR {.unnumbered}

<http://cscar.research.umich.edu/>

Consulting for Statistics, Computing and Analytics Research (CSCAR) is a unit of
the Office of the Vice President of Research at the University of Michigan.
CSCAR offers U-M researchers guidance and training in data collection, 
management, and analysis; and in the use of technical software and advanced 
computing in research.

We offer free, one-hour consultations with graduate-level statisticians. To 
request an appointment, you can send an email to
<deskpeople@umich.edu>, or you can fill [this form](https://docs.google.com/forms/d/e/1FAIpQLSei-twcjFkoobUrVwSQTmSxdKKEc1Ub8w5LHmeIZUmTV1wmIg/viewform?pli=1). You can also walk-in for a consultation with one of our Graduate Student Research Assistants (GSRAs). Or you can use [this link](https://calendar.google.com/calendar/u/0/selfsched?sstoken=UUMyTFpCR1RXbmhYfGRlZmF1bHR8ZWNjNGJlMWZlYTA4ZWE5NzYzNmNkNzgyZjUyZDYxNDg) to 
self-schedule an appointment with a GSRA at your own convenience. GSRAs are available Monday through Friday, between 9am and 5pm (we close on Tuesdays between noon and 1pm). All of our scheduled appointments can be either remote or in-person.

CSCAR can also help with simple statistical questions through email. You can
write to <stats-consulting@umich.edu>.

If you have any questions or comments about these notes, you can contact Abner Heredia Bustos (<abnerhb@umich.edu>).


## Acknowledgments {.unnumbered}

These notes have evolved over the years thanks to Abner Heredia Bustos, Josh 
Errickson, Xiru Lyu, and Chris Andrews.

This material was created for use in workshops and short courses presented by
faculty and staff from the Consulting for Statistics, Computing & Analytics
Research (CSCAR) unit at the University of Michigan.
